title: kw7oe
description: >- # this means to ignore newlines until "baseurl:"
  Just a normal guy who like to code.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: kw7oe
github_username:  kw7oe

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
paginate: 5
paginate_path: "/blog/page-:num"
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
